### ISSUE TITLE
Add "DO NOT EDIT!" comment to `resolvers.ts` file

### ISSUE THREAD

**Issue by schickling** [prisma/graphql-resolver-codegen#41]

**Comment by parammittal16** [comment]
Sir, plz I want to work on this

**Comment by divyenduz** [comment]
@parammittal16 : Thanks for showing interest on this one. Please reach out to me in prisma.slack.com | I will help you get started on this :)

**Comment by divyenduz** [comment]
If you are comfortable to take this up already! Then feel free to raise a PR. 
Please let me know if you need any information to get started.
