### ISSUE TITLE
Scaffold import for Context in TypeMap has a case typo

### ISSUE THREAD

**Issue by herkulano** [prisma/graphql-resolver-codegen#54]
`import { Context } from './context'` should be `import { Context } from './Context'`

This causes a typing error in case-sensitive file systems.

**Comment by divyenduz** [comment]
Fixed via https://github.com/prisma/graphql-resolver-codegen/commit/fa4f0fde58b2dc2c2aededdb805a5f96cb0a42d9

This is available in the latest `beta` - `npm install -g graphql-resolver-codegen@beta`
