### ISSUE TITLE
Flexible export configuration syntax

### ISSUE THREAD

**Issue by maticzav** [prisma/graphql-resolver-codegen#81]
Hey 👋,

We think that we'll eventually need a more sophisticated mechanism to define `output.resolvers` and `output.models`. An opinionated mechanism is an option but we should aim for good defaults rather than making such decisions at the current stage of `graphqlgen`

We thought something similar to `{typeName}` could work quite nicely but there might be a better solution. 🙂

**Comment by schickling** [comment]
Superseded by https://github.com/prisma/graphql-resolver-codegen/issues/106.
